version: "3.8"

services:
  bot:
    build: .

    volumes:
      - data:/app/data/dynamic

    environment:
      TOKEN: /run/secrets/token

    secrets:
      - token

secrets:
  token:
    file: ./secrets/token

volumes:
  data: